repos:
- repo: https://github.com/dnephin/pre-commit-golang.git
  rev: ac0f6582d2484b3aa90b05d568e70f9f3c1374c7
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
